[build]
builder = "dockerfile"
dockerfile = "./ACME.CargoExpress.API/Dockerfile"



[deploy]
startCommand = "dotnet ACME.CargoExpress.API.dll"
restartPolicyType = "always"
healthCheckPath = "/health"